<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>1765687f-1c4a-4082-8e96-3d22788aa41b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99ff42e1-87f8-4db3-abde-28e3f2c5e9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8c0e96b4-27d5-43cc-a63e-4e9bba9c2f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>92005d45-2dda-47b9-bdcf-46949d45d446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57ee9134-4103-46f2-90b4-71d9c5ed794d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-ripple font-condensed hover:bg-opacity-90 outline-none transition-all w-full md:w-1/5 md:rounded-l-none h-11 md:h-15 md:py-0 font-normal hidden md:block et-btn-accent md:text-3xl text-2xl rounded py-2 mb-10 md:mb-0 ng-tns-c105-4</value>
      <webElementGuid>f88c43ef-f2b3-4a91-b7e7-472f666d7fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search </value>
      <webElementGuid>39db6ab3-7f0e-4471-922c-1263ad846d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;cdk-global-scrollblock&quot;]/body[@class=&quot;fuse-splash-screen-hidden light theme-fejobs&quot;]/app-root[1]/layout[@class=&quot;ng-star-inserted&quot;]/modern-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col w-full h-screen ng-star-inserted&quot;]/div[@class=&quot;w-full&quot;]/landing-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col items-center justify-start w-full overflow-x-hidden bg-white&quot;]/div[@class=&quot;et-background w-full&quot;]/div[@class=&quot;bg-warn md:bg-transparent w-full&quot;]/et-home-banner[1]/div[@class=&quot;pt-8 md:pt-14 md:pb-22 relative bannerWrap w-full ng-star-inserted&quot;]/search[@class=&quot;ng-tns-c105-4 search-appearance-bar ng-star-inserted&quot;]/form[@class=&quot;ng-tns-c105-4 ng-untouched ng-valid ng-star-inserted ng-dirty&quot;]/div[@class=&quot;md:px-5 lg:px-8 px-3 md:pt-6 md:pb-4 lg:w-280 lg:mx-auto md:bg-warn md:mx-4 md:rounded-md ng-tns-c105-4&quot;]/div[@class=&quot;md:flex items-center justify-between ng-tns-c105-4&quot;]/button[@class=&quot;mat-ripple font-condensed hover:bg-opacity-90 outline-none transition-all w-full md:w-1/5 md:rounded-l-none h-11 md:h-15 md:py-0 font-normal hidden md:block et-btn-accent md:text-3xl text-2xl rounded py-2 mb-10 md:mb-0 ng-tns-c105-4&quot;]</value>
      <webElementGuid>1f002190-b63c-4cb4-b4fe-36015912fbc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>2b77593e-1358-4321-b111-f4d63a7dfb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::button[2]</value>
      <webElementGuid>58e1eb31-3c5e-4367-9497-500ce12aecfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[1]/preceding::button[1]</value>
      <webElementGuid>6787908e-e99d-4f67-9306-60570f627503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>b0a6deb6-5700-4e11-a164-eafa55858df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>abd46400-8e1e-4f23-adee-c4d6f747a76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Search ' or . = 'Search ')]</value>
      <webElementGuid>e9b580de-4f16-4836-9d59-72eedef1e1fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
