<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>48b4d476-cee0-4a99-98bd-0eb4f2f9c6af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top-scroll']/div[2]/div/div/div/div[2]/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Fejobs&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0d6676e4-4d75-41fe-a29d-46fe50afc1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/UI/Default/Images/Home/fejobs-logo-white.svg</value>
      <webElementGuid>f7dd8f5b-0c98-4556-a069-ec81a44893d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Fejobs</value>
      <webElementGuid>b63b1933-3acf-421d-ab71-9ff7ffa8c1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-scroll&quot;)/div[@class=&quot;main-foot-divhold&quot;]/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;header-fullwidth&quot;]/div[@class=&quot;main-menu-hold&quot;]/div[@class=&quot;header-fullwidth&quot;]/div[@class=&quot;main-menu-hold&quot;]/div[@class=&quot;container-fluid responsive-nav-head&quot;]/div[@class=&quot;header-container&quot;]/div[@class=&quot;mainnav&quot;]/a[@class=&quot;Fejobs logosm-hold&quot;]/img[1]</value>
      <webElementGuid>9885f730-729f-4fa3-bd10-e6263d52779a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[2]/div/div/div/div[2]/div/div/div/div/a/img</value>
      <webElementGuid>52d39a49-4e16-4dd1-be18-b1674f1ef248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Fejobs']</value>
      <webElementGuid>c04c55bb-7e8c-44ff-abb1-b8e520c34681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>86c01ade-a32c-4495-9f08-919c5f7a9b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/UI/Default/Images/Home/fejobs-logo-white.svg' and @alt = 'Fejobs']</value>
      <webElementGuid>ad3fd793-db51-4998-87bd-c7af02ca2543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
