<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Early Careers Teachers Community</name>
   <tag></tag>
   <elementGuidId>fbd8844f-36a0-4eb8-9dc0-9a632fdda2f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top-scroll']/div/div/div/div[3]/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>100d3361-3712-4601-a4ad-ff659cd6db8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Early Careers Teachers Community</value>
      <webElementGuid>9366aa78-636b-4615-aa06-0bb02f06c480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-scroll&quot;)/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;main-foot-divhold&quot;]/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;searchcontainer lanndingZoneSearchContent&quot;]/div[@class=&quot;innersearchcon&quot;]/div[@class=&quot;search-inner-hold&quot;]/div[@class=&quot;midcontent search-main-section  landingZonemidcontent&quot;]/h1[1]</value>
      <webElementGuid>e4948dca-b2f9-4b07-9ffb-a5c9dd034006</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div/div/div/div[3]/div/div/div/h1</value>
      <webElementGuid>f4c5614d-0d75-4650-bf04-cc61f6cbe657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Options'])[2]/following::h1[1]</value>
      <webElementGuid>49fc15de-a46d-40bb-8282-0f98b75f0e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[4]/following::h1[1]</value>
      <webElementGuid>61d916f9-435c-407e-9ddb-2ce0393e81cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Early Careers Teachers Community']/parent::*</value>
      <webElementGuid>e0e450b9-2daa-417d-bee5-5020fbaaac7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>cf583818-b2fc-4db5-899a-3231734f71cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Early Careers Teachers Community' or . = 'Early Careers Teachers Community')]</value>
      <webElementGuid>e2949810-f021-4228-bd05-ff2715fa4375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
