<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign out</name>
   <tag></tag>
   <elementGuidId>e86f075d-328f-47e0-9ee1-e12e49223bd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.py-2.px-4.text-black.text-lg.font-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-menu-panel-2']/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e5c83c9-8097-4937-bcdc-8c3af7e0997c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2 px-4 text-black text-lg font-bold</value>
      <webElementGuid>2898db59-e97f-43e6-b871-51ed2d30d2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sign out </value>
      <webElementGuid>0fce0548-8e33-4323-81d3-8b3a05be4b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-2&quot;)/div[@class=&quot;mat-menu-content ng-tns-c56-7&quot;]/div[@class=&quot;flex justify-end pr-4 ng-tns-c56-7 ng-star-inserted&quot;]/button[@class=&quot;py-2 px-4 text-black text-lg font-bold&quot;]</value>
      <webElementGuid>ecc9e404-9b73-4e9e-a369-8f258a946d69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-2']/div/div[2]/button</value>
      <webElementGuid>b990d8a0-c0cb-492f-89fc-852c66f5c966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Talent Pools'])[1]/following::button[1]</value>
      <webElementGuid>2d8fe7c2-83b3-47d2-86d1-23100733ef89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preference Centre'])[1]/following::button[1]</value>
      <webElementGuid>c0604638-1091-4397-ab35-dd135e74d5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign out']/parent::*</value>
      <webElementGuid>a2542130-b02e-4fb8-aa32-309889321154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/button</value>
      <webElementGuid>93682b29-bef8-4755-8304-c3ca3b8ae9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Sign out ' or . = ' Sign out ')]</value>
      <webElementGuid>f601403f-cc35-4ff9-b699-8df6212b96f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
