<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Support the future of your industry</name>
   <tag></tag>
   <elementGuidId>7fac27ee-3d49-427a-9e29-2248b384848d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section-240042']/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.section-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>9064c88a-5e92-44c3-b392-617a7da0047d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-title</value>
      <webElementGuid>c2f23fc5-1497-4616-88b4-4f0df0a97324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Support the future of your industry</value>
      <webElementGuid>313c0a4c-4475-4d15-9e18-fd812392aad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-240042&quot;)/div[@class=&quot;container&quot;]/h3[@class=&quot;section-title&quot;]</value>
      <webElementGuid>6398c0a0-4897-4020-ad9b-ba6b02f9949d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-240042']/div/h3</value>
      <webElementGuid>d91a0a1e-1a35-42f2-8972-ab1efc98a67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support the future workforce of your sector'])[1]/following::h3[1]</value>
      <webElementGuid>9b06c0b1-a960-4882-a895-8e97b0e5840c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAKING TEACHING FURTHER'])[1]/following::h3[2]</value>
      <webElementGuid>6cf34e76-bcd4-443c-92ba-08d3df4bfc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is Taking Teaching Further?'])[1]/preceding::h3[1]</value>
      <webElementGuid>9cd2e60f-55f8-4897-8aa8-f1f19cadf058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='business'])[1]/preceding::h3[1]</value>
      <webElementGuid>be21421d-df9b-4722-aeec-9ba1f10205f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Support the future of your industry']/parent::*</value>
      <webElementGuid>cd8be752-314f-4a6f-b27f-f495926cca61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h3</value>
      <webElementGuid>6059664a-4697-45ed-bc8b-61b6688f9be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Support the future of your industry' or . = 'Support the future of your industry')]</value>
      <webElementGuid>af041d83-98e2-404e-8347-c3ff7f9b5325</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
