<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create new job alert</name>
   <tag></tag>
   <elementGuidId>b1ee9169-9cb5-4ab7-acde-d8d8243e88d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top-scroll']/div[5]/div/div[4]/div[2]/div/div/div[2]/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.apply-btn.submit-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1448e8da-86c0-4fb0-994f-3c1587640101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jobseekers/jbe?populateJBE=false</value>
      <webElementGuid>cbac2567-845a-49ae-b965-e65db874dc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn apply-btn submit-btn</value>
      <webElementGuid>f022721e-d2ee-4c52-a15e-624a41e7bd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create new job alert</value>
      <webElementGuid>407e958d-fe41-4043-999d-d0b5d3383cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-scroll&quot;)/div[@class=&quot;main-foot-divhold candidate-indexhold&quot;]/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;container-fluid account-detail-hold&quot;]/div[@class=&quot;container seeker-wrap&quot;]/div[@class=&quot;col-md-12 job-alert-page&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-sm-10 col-xs-12&quot;]/div[@class=&quot;box-theme-7&quot;]/div[@class=&quot;pull-right&quot;]/a[@class=&quot;btn apply-btn submit-btn&quot;]</value>
      <webElementGuid>033b9e9d-882a-4cb3-a8bc-023e78214a30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[5]/div/div[4]/div[2]/div/div/div[2]/div[2]/div/a</value>
      <webElementGuid>0c524e12-fc57-47a2-8722-0f5828f7f746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create new job alert')]</value>
      <webElementGuid>4400720c-cdb9-498c-b324-31252c1fade7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('You', &quot;'&quot;, 've got mail')])[1]/following::a[1]</value>
      <webElementGuid>474bb972-26b2-49a5-a415-0088541e1892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/preceding::a[1]</value>
      <webElementGuid>77a40ce0-1b05-436a-89fc-9d13a8219559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job alert'])[1]/preceding::a[1]</value>
      <webElementGuid>ec9d5f0e-f0bd-452f-ba85-837ef708baf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create new job alert']/parent::*</value>
      <webElementGuid>d9035247-78bf-461a-9c29-79b60ad66cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/jobseekers/jbe?populateJBE=false')]</value>
      <webElementGuid>91e7c69a-76e7-41cc-ae29-473132910c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div/a</value>
      <webElementGuid>e82704df-1033-43fb-9c9b-f207345bc4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/jobseekers/jbe?populateJBE=false' and (text() = 'Create new job alert' or . = 'Create new job alert')]</value>
      <webElementGuid>d7c3b207-b6e7-4db7-94a9-5c21ffb09c49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
