<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>931f7894-afd1-47c7-b8b7-c696391774c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top-scroll']/div[4]/div/div[2]/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Eteach&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ae3d3bf0-262c-4534-8d8f-35ddfb9aeab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/UI/Default/Images/eteach/logo-text.svg</value>
      <webElementGuid>4802459e-d6d8-4c1d-8d6b-5aa52866019e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Eteach</value>
      <webElementGuid>9a5c9fb8-f9eb-4194-a7f2-cc30e96074c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-scroll&quot;)/div[@class=&quot;main-foot-divhold&quot;]/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;header-fullwidth&quot;]/div[@class=&quot;main-menu-hold&quot;]/div[@class=&quot;container-fluid responsive-nav-head&quot;]/div[@class=&quot;header-container&quot;]/div[@class=&quot;mainnav&quot;]/a[@class=&quot;Eteachnew logosm-hold&quot;]/img[1]</value>
      <webElementGuid>98d3d9d6-3e2d-4bf2-9c13-8f6622eda4f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[4]/div/div[2]/div/div/div/div/a/img</value>
      <webElementGuid>b5545ff4-90e7-46a0-93f2-9a082ba341c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Eteach']</value>
      <webElementGuid>f634f182-fc87-4412-8ea5-e58f584cce24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a76547cc-a56a-4324-a34d-436cd0e30483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/UI/Default/Images/eteach/logo-text.svg' and @alt = 'Eteach']</value>
      <webElementGuid>85fbf8c4-e089-4efd-bd7d-1eaad8f9464d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
