<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>a0446d2c-67d3-487d-a34b-79d13caa5fdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.owl-dot.active.ng-star-inserted > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e0d35c14-6213-4e13-9272-567032b660d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;fuse-splash-screen-hidden light theme-eteach&quot;]/app-root[1]/layout[@class=&quot;ng-star-inserted&quot;]/modern-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col w-full h-screen ng-star-inserted&quot;]/div[@class=&quot;w-full&quot;]/landing-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col items-center justify-start w-full overflow-x-hidden bg-white&quot;]/div[@class=&quot;w-full mb-6 md:mb-10&quot;]/ad-banner[1]/div[@class=&quot;lg:w-280 lg:mx-auto px-3 md:px-4 lg:px-0 pb-7&quot;]/div[@class=&quot;z-49 dark:shadow-none dark:border-b dark:bg-transparent print:hidden relative banner ng-star-inserted&quot;]/owl-carousel-o[1]/div[@class=&quot;owl-carousel owl-theme owl-loaded owl-responsive owl-drag&quot;]/div[@class=&quot;owl-dots ng-star-inserted&quot;]/div[@class=&quot;owl-dot active ng-star-inserted&quot;]/span[1]</value>
      <webElementGuid>77a59fd0-93c7-4a54-ba88-1ea1be927036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/span</value>
      <webElementGuid>2bb8fcc6-8f2f-4de6-a9f3-b6e60934ddb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
