<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Early Careers Teachers Community</name>
   <tag></tag>
   <elementGuidId>801ac045-498c-4dc7-a42a-2048344ac12b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top-scroll']/div/div/div/div[3]/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>949b46da-92b8-4a6d-b0d3-dd57d793498f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Early Careers Teachers Community</value>
      <webElementGuid>abb81c57-41cc-4f60-8c53-bca5d8c03dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-scroll&quot;)/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;main-foot-divhold&quot;]/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;searchcontainer lanndingZoneSearchContent&quot;]/div[@class=&quot;innersearchcon&quot;]/div[@class=&quot;search-inner-hold&quot;]/div[@class=&quot;midcontent search-main-section  landingZonemidcontent&quot;]/h1[1]</value>
      <webElementGuid>78bab432-bb9a-45ff-bdad-74efb88d22d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div/div/div/div[3]/div/div/div/h1</value>
      <webElementGuid>3c036782-c177-433d-9ad1-f0d7a0fa90ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Options'])[2]/following::h1[1]</value>
      <webElementGuid>fc095fb8-d97d-4403-a081-6412cef52601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Call us: 0845 226 1906'])[1]/following::h1[1]</value>
      <webElementGuid>14057016-08c6-4d64-b2c0-52e57623363f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Early Careers Teachers Community']/parent::*</value>
      <webElementGuid>98b094e9-3938-49c5-9bf7-a5ebd22ba6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>06d91027-f9bc-4ebe-94f3-e42b00891ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Early Careers Teachers Community' or . = 'Early Careers Teachers Community')]</value>
      <webElementGuid>5e91f3ad-f662-4ba4-bdec-6bd5df707ff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
