<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_LoginPassword</name>
   <tag></tag>
   <elementGuidId>a27ede36-b8de-4d87-af9d-c3573f9ec66c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LoginPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b8dabf5-4994-44a1-93b2-8cdc01bfe3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>b8505fff-fca3-4a5d-bc52-a3b4c2fcd2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginPassword</value>
      <webElementGuid>ed285bcf-54c8-4c46-a567-53c7f119d947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginPassword</value>
      <webElementGuid>cde51068-b371-4cf2-ac5a-b5ecb957f357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>33193495-8ddc-4b60-b2d4-1be9380c3145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b5721867-816d-48bb-bd1b-35ad24eb06cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginPassword&quot;)</value>
      <webElementGuid>63e984fe-878c-485d-96c2-e8021d96dca6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginPassword']</value>
      <webElementGuid>31b6efb3-718d-4aac-a5ae-69ce21eb696f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comments-logout']/form/div[4]/div/div/fieldset/div[2]/div/input</value>
      <webElementGuid>68961461-b238-4348-be15-e29fe829daf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/input</value>
      <webElementGuid>79e132bb-5e67-4421-aedf-31699b7fc2f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LoginPassword' and @name = 'LoginPassword' and @placeholder = 'Password' and @type = 'password']</value>
      <webElementGuid>0f8cdf89-4c29-48b1-87ba-e4ff4549a680</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
