<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Resources</name>
   <tag></tag>
   <elementGuidId>6c76876a-a5f0-4166-bd5e-2b7fffb79b1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Career Pathways'])[1]/following::span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c62f8a01-85d1-4a41-9b90-8b21940f1d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Resources </value>
      <webElementGuid>6cd0c03c-c375-4f5d-884d-95825286de07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;fuse-splash-screen-hidden light theme-fejobs&quot;]/app-root[1]/layout[@class=&quot;ng-star-inserted&quot;]/modern-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col w-full h-screen ng-star-inserted&quot;]/div[@class=&quot;relative bg-primary-500 w-full&quot;]/div[@class=&quot;flex text-white flex-0 items-center lg:w-320 lg:mx-auto h-15 px-3 md:px-4 z-49 dark:shadow-none dark:border-b dark:bg-transparent print:hidden&quot;]/fuse-horizontal-navigation[@class=&quot;mt-1 mr-2 ng-tns-c63-0 ng-star-inserted&quot;]/div[@class=&quot;fuse-horizontal-navigation-wrapper ng-tns-c63-0&quot;]/fuse-horizontal-navigation-branch-item[@class=&quot;fuse-horizontal-navigation-menu-item ng-tns-c63-0 ng-star-inserted&quot;]/button[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;fuse-horizontal-navigation-item-wrapper ng-star-inserted&quot;]/div[@class=&quot;mat-tooltip-trigger fuse-horizontal-navigation-item&quot;]/div[@class=&quot;fuse-horizontal-navigation-item-title-wrapper&quot;]/div[@class=&quot;fuse-horizontal-navigation-item-title&quot;]/span[1]</value>
      <webElementGuid>432521f2-8bcd-4af2-9030-7922856628c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career Pathways'])[1]/following::span[2]</value>
      <webElementGuid>fdea96dd-30be-4db6-99c5-527cd36ecd38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs'])[1]/following::span[3]</value>
      <webElementGuid>11fcc68b-2812-43e5-a300-d314ef8d2e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidates'])[1]/preceding::span[2]</value>
      <webElementGuid>d80c782a-966f-4f18-819e-b1599ddfc090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employers'])[1]/preceding::span[3]</value>
      <webElementGuid>8fea3aec-f4e6-4c54-82f4-732212129366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resources']/parent::*</value>
      <webElementGuid>09f5c061-ada2-44f0-afb6-e34678d748b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fuse-horizontal-navigation-branch-item[2]/button/div/div/div/div/span</value>
      <webElementGuid>bc12f185-f2b4-4dde-bd65-ab842ae9d9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Resources ' or . = ' Resources ')]</value>
      <webElementGuid>57ac8008-3497-4393-988e-af41b3e372a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
