<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Support the future of your industry</name>
   <tag></tag>
   <elementGuidId>c1f07f9f-2668-4563-a654-7b3d1ef900e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section-240042']/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.section-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>926240ed-edc2-4231-9957-1c412c1dae23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-title</value>
      <webElementGuid>e27ab794-99b1-491d-9011-dd670df12e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Support the future of your industry</value>
      <webElementGuid>b47d16ca-348e-4d0c-be0a-eafedcffb1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-240042&quot;)/div[@class=&quot;container&quot;]/h3[@class=&quot;section-title&quot;]</value>
      <webElementGuid>9f015ed1-7478-4067-9508-e2548d52578f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-240042']/div/h3</value>
      <webElementGuid>d4e4d6ad-0df0-40c7-9941-146660c049fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support the future workforce of your sector'])[1]/following::h3[1]</value>
      <webElementGuid>f0480355-d52e-4358-87d2-a45bc2a0bc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAKING TEACHING FURTHER'])[1]/following::h3[2]</value>
      <webElementGuid>28a31a2a-4dd5-42ae-afc3-57fb0d94e8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is Taking Teaching Further?'])[1]/preceding::h3[1]</value>
      <webElementGuid>aa767c86-0c1c-4ec1-8f2b-d60c900a5972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='business'])[1]/preceding::h3[1]</value>
      <webElementGuid>d65a7947-1f41-41cc-8527-51d1745aeb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Support the future of your industry']/parent::*</value>
      <webElementGuid>5550c0d9-1e06-45ef-993b-ba39a849bddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h3</value>
      <webElementGuid>b76b4640-325d-4ab2-b637-deab616727a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Support the future of your industry' or . = 'Support the future of your industry')]</value>
      <webElementGuid>48d5e85b-be1c-4970-b248-135c1d1d4b4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
