<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Eteach is an education technology busine_147cbe</name>
   <tag></tag>
   <elementGuidId>a436763b-5df0-4284-8aeb-dc108db5663a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top-scroll']/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7f5fd3ee-1bc3-4360-b8f3-57f555e09b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>121d2340-a181-4ec9-886d-21a5e7e9902d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eteach is an education technology business dedicated to providing online recruitment advertising, direct recruitment services and recruitment software to more than 7,500 schools and colleges globally</value>
      <webElementGuid>0ff31f63-69e7-4ce7-a95b-a09fbd5e0c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-scroll&quot;)/div[@class=&quot;main-foot-divhold&quot;]/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;container-fluid account-detail-hold&quot;]/div[@class=&quot;umb-grid&quot;]/div[@class=&quot;grid-section&quot;]/div[@class=&quot;promo-text&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row clearfix&quot;]/div[@class=&quot;col-md-12 column&quot;]/div[@class=&quot;pt-50 pb-50&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-offset-1 col-sm-10 text-center&quot;]/h1[@class=&quot;heading&quot;]</value>
      <webElementGuid>c4487cb8-b94c-4fbc-9221-016349f532cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/h1</value>
      <webElementGuid>58014fd1-621c-4f0c-8a56-4f16f7de277a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Call me back'])[2]/following::h1[1]</value>
      <webElementGuid>5a38fc8e-db4a-4fc0-aee3-b9b76e6847e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Packages'])[2]/following::h1[1]</value>
      <webElementGuid>92a6fd84-2390-4ec6-a87f-06d25689b5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our services'])[1]/preceding::h1[1]</value>
      <webElementGuid>2b7a64be-3251-47a3-a95b-57bb68c733c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advertise with us'])[1]/preceding::h1[1]</value>
      <webElementGuid>bf3cc9bf-f2a0-4d23-867c-f348d1d471b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eteach is an education technology business dedicated to providing online recruitment advertising, direct recruitment services and recruitment software to more than 7,500 schools and colleges globally']/parent::*</value>
      <webElementGuid>7920854d-aef2-4913-9056-5f6ef20cde7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>f26b9d9a-685a-4565-8a56-6741829b53cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Eteach is an education technology business dedicated to providing online recruitment advertising, direct recruitment services and recruitment software to more than 7,500 schools and colleges globally' or . = 'Eteach is an education technology business dedicated to providing online recruitment advertising, direct recruitment services and recruitment software to more than 7,500 schools and colleges globally')]</value>
      <webElementGuid>c3968342-62aa-4d8b-afa9-25e1f2b6210a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
