<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>80dd897a-b088-4384-841b-4c3525a21d1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top-scroll']/div[2]/div/div/div/div[2]/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Fejobs&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aa1e7c89-321c-41dd-872c-877ded2b0472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/UI/Default/Images/Home/fejobs-logo-white.svg</value>
      <webElementGuid>ff93b219-f7eb-45bc-b063-406e98bdfd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Fejobs</value>
      <webElementGuid>65681b37-d4ba-4c0b-8266-ba5863636084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-scroll&quot;)/div[@class=&quot;main-foot-divhold&quot;]/div[@class=&quot;container-fluid whole-wrap blog-menu-section&quot;]/div[@class=&quot;header-fullwidth&quot;]/div[@class=&quot;main-menu-hold&quot;]/div[@class=&quot;header-fullwidth&quot;]/div[@class=&quot;main-menu-hold&quot;]/div[@class=&quot;container-fluid responsive-nav-head&quot;]/div[@class=&quot;header-container&quot;]/div[@class=&quot;mainnav&quot;]/a[@class=&quot;Fejobs logosm-hold&quot;]/img[1]</value>
      <webElementGuid>299e245f-1f89-4b90-aa7d-05ac54eb620e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[2]/div/div/div/div[2]/div/div/div/div/a/img</value>
      <webElementGuid>668ebec8-ca5b-4193-8d6b-90cafc035c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Fejobs']</value>
      <webElementGuid>640435cf-54f0-4217-a9a6-0eb35a3166c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>6640ae9b-42ae-4a09-8eff-4871d37e0540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/UI/Default/Images/Home/fejobs-logo-white.svg' and @alt = 'Fejobs']</value>
      <webElementGuid>44fee6d3-067f-4ada-9fe7-53fc52f70ed4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
