<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign out</name>
   <tag></tag>
   <elementGuidId>c8ff3bc8-b9dd-494a-9fff-0d11b9dff54e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.d-logout.open</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top-scroll']/div[4]/div/div[2]/div/div/div/div/div[3]/ul/li[4]/div/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d8c9c82-bea3-492e-ab46-ceb399f163ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jobseekers/logout/</value>
      <webElementGuid>0b94f76d-71ba-4a96-8d0e-f83422f238e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-logout open</value>
      <webElementGuid>25be4664-a096-4438-b72b-4a4104c87722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign out</value>
      <webElementGuid>fe97c76f-a7ce-4780-b9de-1f2e0bc52e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-scroll&quot;)/div[@class=&quot;main-foot-divhold&quot;]/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;header-fullwidth menu-toggle&quot;]/div[@class=&quot;main-menu-hold&quot;]/div[@class=&quot;container-fluid responsive-nav-head headerOverlay&quot;]/div[@class=&quot;header-container&quot;]/div[@class=&quot;mainnav&quot;]/div[@class=&quot;rightSec&quot;]/ul[@class=&quot;res-menu-sec eteachRightNav&quot;]/li[@class=&quot;mmenu no-bdr-menu account-btn-main&quot;]/div[@class=&quot;main-acc&quot;]/div[@class=&quot;acc-menu-hold new-menu&quot;]/div[@class=&quot;last&quot;]/a[@class=&quot;d-logout open&quot;]</value>
      <webElementGuid>8c307083-cab8-4352-99ac-0e54362008ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[4]/div/div[2]/div/div/div/div/div[3]/ul/li[4]/div/div[2]/div[2]/a</value>
      <webElementGuid>eff55382-6c5a-41ce-b20b-9d5e8c20dffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Sign out')])[2]</value>
      <webElementGuid>509747a7-bbd6-4f54-8d7c-356a245b496f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='device_hub'])[1]/following::a[1]</value>
      <webElementGuid>9a294e69-ea6f-4fc8-87de-6e5098097e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[2]/preceding::a[1]</value>
      <webElementGuid>27a2dfec-5d3d-4a6c-80d9-69b88a820d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/jobseekers/logout/')])[2]</value>
      <webElementGuid>fb96d7bf-b052-4c21-9d70-620f1739ced9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div[2]/div[2]/a</value>
      <webElementGuid>a238a88f-3160-4a05-8ccf-c4cbe0a32a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/jobseekers/logout/' and (text() = 'Sign out' or . = 'Sign out')]</value>
      <webElementGuid>19678e20-f1a7-4363-9c7e-084ca8f68b9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
