<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FAQs</name>
   <tag></tag>
   <elementGuidId>8f28e4c2-df68-4f40-88c2-02be980fc55d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mat-tooltip-trigger.fuse-horizontal-navigation-item.ng-star-inserted.cdk-focused.cdk-mouse-focused > div.fuse-horizontal-navigation-item-title-wrapper.ng-star-inserted > div.fuse-horizontal-navigation-item-title.horizontal-nav-content-title > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-menu-panel-1']/div/div[2]/fuse-horizontal-navigation-basic-item/div/a/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd23e7bf-4ac6-43c5-bc9c-9df9d3c04958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> FAQs </value>
      <webElementGuid>36eae2f2-f274-49e0-b8ea-e51df34af589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-1&quot;)/div[@class=&quot;mat-menu-content ng-tns-c56-3&quot;]/div[@class=&quot;mat-focus-indicator fuse-horizontal-navigation-menu-item mat-menu-item ng-tns-c56-3 ng-star-inserted&quot;]/fuse-horizontal-navigation-basic-item[1]/div[@class=&quot;fuse-horizontal-navigation-item-wrapper fuse-horizontal-navigation-item-has-subtitle horizontal-nav-content-wrapper ng-star-inserted&quot;]/a[@class=&quot;mat-tooltip-trigger fuse-horizontal-navigation-item ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;fuse-horizontal-navigation-item-title-wrapper ng-star-inserted&quot;]/div[@class=&quot;fuse-horizontal-navigation-item-title horizontal-nav-content-title&quot;]/span[1]</value>
      <webElementGuid>1f3fafbf-f89b-453d-b935-d77a6e31e1b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-1']/div/div[2]/fuse-horizontal-navigation-basic-item/div/a/div[2]/div/span</value>
      <webElementGuid>64699493-ef5d-4b02-8c9b-aa273b427c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access valuable resources from our partners to develop your knowledge'])[1]/following::span[1]</value>
      <webElementGuid>5922ccb7-e1fe-4231-9a0b-99d1fbeaef5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CPD'])[1]/following::span[2]</value>
      <webElementGuid>58342027-be4d-48aa-a5a4-ffb44c701f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find solutions to common questions and concerns quickly and easily'])[1]/preceding::span[1]</value>
      <webElementGuid>5a52dbe8-9c5c-45fa-9753-8e88354642a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teaching in the UK'])[1]/preceding::span[2]</value>
      <webElementGuid>c1a2b4ba-5ecb-4af2-9694-358f5b616923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fuse-horizontal-navigation-basic-item/div/a/div[2]/div/span</value>
      <webElementGuid>51fae611-2075-45c2-b361-5d655975462b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' FAQs ' or . = ' FAQs ')]</value>
      <webElementGuid>d0b381d5-2311-441d-be86-405722caad3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
