<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_More Options_term</name>
   <tag></tag>
   <elementGuidId>83b2e6ff-1201-4c17-b586-f57358aed127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchbx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchbx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b59ec45e-c765-4ce5-8fd8-d8ef9b65c81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a80dcee2-cc90-45cc-849b-d24d439c23d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>term</value>
      <webElementGuid>8713bbe9-2cec-425f-9572-77caa93e6992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchfield</value>
      <webElementGuid>2bca665c-e4a0-4350-975f-cb599398e422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Blog</value>
      <webElementGuid>fc5e0939-e28a-4517-9ba5-e44bc582d428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchbx</value>
      <webElementGuid>b1cc53ca-a990-404c-8482-8b57da0ce464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>updateSection();</value>
      <webElementGuid>a7ed27e4-3dcf-4674-aeef-e869024f5926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ddd026b-cfcc-4a58-9721-6168ee51e74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchbx&quot;)</value>
      <webElementGuid>00bbbb0e-8017-4936-829e-32f982ec96d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchbx']</value>
      <webElementGuid>de427540-8f0e-412a-83fe-d1523a6d790c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[2]/div/div[2]/div[2]/div/div/ul/li/div/form/input</value>
      <webElementGuid>43a7e970-953f-465e-b6ab-c3370978b66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>f0706cf8-d47f-441c-b8f4-126c8b695e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'term' and @placeholder = 'Search Blog' and @id = 'searchbx']</value>
      <webElementGuid>4ea79614-f542-4492-8fe1-6604b1554184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
