<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cookie settings_onetrust-close-btn-h_cbb2a4</name>
   <tag></tag>
   <elementGuidId>1b1fa1bc-e3ea-4c05-9e3e-e5fe334f5acd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.onetrust-close-btn-handler.banner-close-button.ot-close-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='onetrust-close-btn-container']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4b21c36-6394-4f2c-81b6-ec6f43a7c2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onetrust-close-btn-handler banner-close-button ot-close-icon</value>
      <webElementGuid>7f6e20cd-20a4-4c5b-b685-714fb7772eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>933e02ec-688b-4ee4-9d9c-cafae18f42d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onetrust-close-btn-container&quot;)/button[@class=&quot;onetrust-close-btn-handler banner-close-button ot-close-icon&quot;]</value>
      <webElementGuid>7147cb6c-e97a-457e-9c9c-36748211efd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onetrust-close-btn-container']/button</value>
      <webElementGuid>0de4eff8-5fd3-4b4e-bcf4-e7b52e4f42f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>3edb2bfd-d1d3-440b-8081-ba1be6fa39f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
