<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>8cd61af2-774d-4b78-9148-e195832bd239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7ad0cdac-d32e-44fd-8c3d-17f26a97ab0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b4bb30a8-50bc-4f65-bf19-6eecae664d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4a166c5b-c071-4e5f-9f6e-bd1656ee2718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac0de23c-9b65-42f1-942c-eb27b1f89801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-ripple font-condensed hover:bg-opacity-90 outline-none transition-all w-full md:w-1/5 md:rounded-l-none h-11 md:h-15 md:py-0 font-normal hidden md:block et-btn-accent md:text-3xl text-2xl rounded py-2 mb-10 md:mb-0 ng-tns-c105-4</value>
      <webElementGuid>242dd72e-d76f-400f-b6f2-de207f445c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search </value>
      <webElementGuid>135ea1d2-449a-49a4-baf9-0afb56af3b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;cdk-global-scrollblock&quot;]/body[@class=&quot;fuse-splash-screen-hidden light theme-eteach&quot;]/app-root[1]/layout[@class=&quot;ng-star-inserted&quot;]/modern-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col w-full h-screen ng-star-inserted&quot;]/div[@class=&quot;w-full&quot;]/landing-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col items-center justify-start w-full overflow-x-hidden bg-white&quot;]/div[@class=&quot;et-background w-full&quot;]/div[@class=&quot;bg-warn md:bg-transparent w-full&quot;]/et-home-banner[1]/div[@class=&quot;pt-8 md:pt-14 md:pb-22 relative bannerWrap w-full ng-star-inserted&quot;]/search[@class=&quot;ng-tns-c105-4 search-appearance-bar ng-star-inserted&quot;]/form[@class=&quot;ng-tns-c105-4 ng-untouched ng-valid ng-star-inserted ng-dirty&quot;]/div[@class=&quot;md:px-5 lg:px-8 px-3 md:pt-6 md:pb-4 lg:w-280 lg:mx-auto md:bg-warn md:mx-4 md:rounded-md ng-tns-c105-4&quot;]/div[@class=&quot;md:flex items-center justify-between ng-tns-c105-4&quot;]/button[@class=&quot;mat-ripple font-condensed hover:bg-opacity-90 outline-none transition-all w-full md:w-1/5 md:rounded-l-none h-11 md:h-15 md:py-0 font-normal hidden md:block et-btn-accent md:text-3xl text-2xl rounded py-2 mb-10 md:mb-0 ng-tns-c105-4&quot;]</value>
      <webElementGuid>286f17db-11da-4a8e-aa00-d20e4f857de7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>78b0dd4d-f620-44c7-902f-233ca1e1a002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::button[2]</value>
      <webElementGuid>13909eee-9cde-42f9-847b-cd9498d30bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[1]/preceding::button[1]</value>
      <webElementGuid>dc007baa-05c3-49aa-8c35-dda95af39b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>e198d983-e4c2-4fc8-afbd-5a467e78f525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Search ' or . = 'Search ')]</value>
      <webElementGuid>b0a6dfcb-1952-49ce-9444-607036a464cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
