<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard</name>
   <tag></tag>
   <elementGuidId>ecd0a400-1206-404a-be3c-9820cc383f7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top-scroll']/div[3]/div/div[4]/div[2]/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.your_account_hold > ul > li > a.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d3c0f114-8197-49d2-85fd-89106291108a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jobseekers/dashboard/</value>
      <webElementGuid>3489d2b2-46d9-4988-ba32-860a0f86e39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>91d1a902-1d31-4173-a59b-2882565b97d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>7efc1d35-9813-4d77-9a7b-ae0a3daaa435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-scroll&quot;)/div[@class=&quot;main-foot-divhold candidate-indexhold&quot;]/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;container-fluid account-detail-hold&quot;]/div[@class=&quot;main-candi-menu&quot;]/div[@class=&quot;myaccount_hold container&quot;]/div[@class=&quot;your_account_hold&quot;]/ul[1]/li[1]/a[@class=&quot;active&quot;]</value>
      <webElementGuid>85ce2337-5930-4784-bfb7-2be3cde7fcb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[3]/div/div[4]/div[2]/div/div/ul/li/a</value>
      <webElementGuid>e6844985-1bad-43d0-b004-17850733c333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Dashboard')])[2]</value>
      <webElementGuid>64e341b5-6c7a-4f5f-8c41-b8585a8bde6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>99265459-ef55-40af-8b04-3c99caedf3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please update your latest CV'])[1]/following::a[2]</value>
      <webElementGuid>b2e36cc8-92a2-4f7a-bd3d-a55219435c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CV/Resume'])[1]/preceding::a[1]</value>
      <webElementGuid>2cf61c63-d0e0-417e-94d0-a604cb32ced0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Alerts'])[1]/preceding::a[2]</value>
      <webElementGuid>8bdb1e22-0cff-488e-a674-7ee9e7050839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/jobseekers/dashboard/')])[3]</value>
      <webElementGuid>9a16ad9c-702e-47d1-91e5-2edf8058bfce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/a</value>
      <webElementGuid>76ce9336-366b-41c3-8fd8-0a478bce2489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/jobseekers/dashboard/' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>9df64295-c4fb-486f-9c48-98df45cb8f50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
