<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard</name>
   <tag></tag>
   <elementGuidId>a9bcbd55-d9c7-4ebe-bb88-8fa97d282e9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.your_account_hold > ul > li > a.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top-scroll']/div[3]/div/div[4]/div[2]/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d1ab155a-0f24-408e-bd7a-4b9160347f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jobseekers/dashboard/</value>
      <webElementGuid>d7600eae-0d30-4189-9155-7f09dbbbff6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>50bdc47e-21e4-489e-a2a9-5aa06c8249cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>0ab13bc6-190f-4602-8f5d-11ccf3ecf0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-scroll&quot;)/div[@class=&quot;main-foot-divhold candidate-indexhold&quot;]/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;container-fluid account-detail-hold&quot;]/div[@class=&quot;main-candi-menu&quot;]/div[@class=&quot;myaccount_hold container&quot;]/div[@class=&quot;your_account_hold&quot;]/ul[1]/li[1]/a[@class=&quot;active&quot;]</value>
      <webElementGuid>b7848423-7daa-45b2-aa71-5b5d430d1500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[3]/div/div[4]/div[2]/div/div/ul/li/a</value>
      <webElementGuid>6c37d738-2a1f-4d8d-aef0-2e57600afceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Dashboard')])[2]</value>
      <webElementGuid>7e783e6d-5717-4aaf-8a59-e1cf50c66f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>db42e071-5dd3-46d5-b17b-5ebde563b69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please update your latest CV'])[1]/following::a[2]</value>
      <webElementGuid>a7a7ba5e-9c92-4e0a-844d-466b2d0129b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CV/Resume'])[1]/preceding::a[1]</value>
      <webElementGuid>075f0c9b-2162-4758-aa16-74d4ea0d4bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Alerts'])[1]/preceding::a[2]</value>
      <webElementGuid>70a660b1-6a8a-4359-8f1a-1e111c213f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/jobseekers/dashboard/')])[3]</value>
      <webElementGuid>2ab571d2-9b17-4c7b-8e89-cfb0cdac89ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/a</value>
      <webElementGuid>236d04cf-371d-4553-a68d-07186b675ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/jobseekers/dashboard/' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>0911a4ac-d48e-479e-a511-e83d4a9c0d01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
