<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cookie settings_onetrust-close-btn-h_cbb2a4</name>
   <tag></tag>
   <elementGuidId>0d147370-8491-4317-b714-78c3b3b8fb33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='onetrust-close-btn-container']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.onetrust-close-btn-handler.banner-close-button.ot-close-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b6da92e-bc9c-410e-a2e6-5345f65af0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onetrust-close-btn-handler banner-close-button ot-close-icon</value>
      <webElementGuid>2afbf0a8-5e1c-4753-af59-08f0f99b768a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>03bcfcc4-32ac-4fc7-bcfc-e128612fb44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onetrust-close-btn-container&quot;)/button[@class=&quot;onetrust-close-btn-handler banner-close-button ot-close-icon&quot;]</value>
      <webElementGuid>e4e55179-7680-4bdc-bda3-51105343462f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onetrust-close-btn-container']/button</value>
      <webElementGuid>cea85295-b84e-48dc-8b9f-25c3e9c454e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>a2c588f3-c37b-4baf-b65e-390687f36da1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
