<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cookie settings_onetrust-close-btn-h_cbb2a4</name>
   <tag></tag>
   <elementGuidId>bdfd58fb-d6e0-4e7c-90ec-cd9cf664095f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.onetrust-close-btn-handler.banner-close-button.ot-close-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='onetrust-close-btn-container']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7572135c-0ccd-4c64-b3cf-92a7b9afbc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onetrust-close-btn-handler banner-close-button ot-close-icon</value>
      <webElementGuid>11a5357e-1b18-4815-ba7d-8ebd05c58058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>c7c631f5-0351-4cb6-8ec4-6d037e0ea5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onetrust-close-btn-container&quot;)/button[@class=&quot;onetrust-close-btn-handler banner-close-button ot-close-icon&quot;]</value>
      <webElementGuid>efd6e5ac-4f74-45e7-8191-4b6759b19573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onetrust-close-btn-container']/button</value>
      <webElementGuid>671b5489-0bfc-4805-a065-6d6b040d1b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>d0389bd6-1d90-42cd-b42f-5e16c774a2cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
