<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_LoginPassword</name>
   <tag></tag>
   <elementGuidId>438b9cd3-07bb-4dc0-911c-ef7432cdde8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LoginPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cc1fc04-9fc2-4726-b927-f151a6be86c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>2399527b-7cd9-40e9-8137-64fe08b27d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginPassword</value>
      <webElementGuid>85af00c2-ee40-4dd9-bd38-782b6e1bc790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginPassword</value>
      <webElementGuid>3b8b37f3-6d99-4724-9de2-c3bdda98032b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>a26d9085-9083-4dc2-9b5d-32477ce7719e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0e2e7cf0-48c8-48e7-97ae-c052cc1a7885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginPassword&quot;)</value>
      <webElementGuid>3d03d388-5aca-4f02-8567-7d9e9319c1ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginPassword']</value>
      <webElementGuid>2a95b0d3-09fa-4221-aba1-985982a953a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comments-logout']/form/div[4]/div/div/fieldset/div[2]/div/input</value>
      <webElementGuid>63ab1046-4ea4-48ea-80a0-1ed045bca1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/input</value>
      <webElementGuid>d9567f8e-a3af-4337-8bf0-5bbca1e4e032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LoginPassword' and @name = 'LoginPassword' and @placeholder = 'Password' and @type = 'password']</value>
      <webElementGuid>54f70812-175a-4f6f-8240-e2b9381cd562</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
