<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_LoginEmail</name>
   <tag></tag>
   <elementGuidId>49a53df4-6b4d-410b-8eb3-6ecbdface3a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LoginEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>850d9ab2-f319-43a9-a412-9bb3939064d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginEmail</value>
      <webElementGuid>d128077a-6915-4d1e-a803-0c6620d0ac26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginEmail</value>
      <webElementGuid>e6ac9dc9-64b1-4e50-bf97-91859a049df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>e20be7ab-ac14-4946-a62a-a62f6f042b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c59ab42-3ca8-4bd8-b5dd-96910e8df90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginEmail&quot;)</value>
      <webElementGuid>b18e8e8c-cbd5-4be6-b906-6b670da1e9dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginEmail']</value>
      <webElementGuid>ff99c9b2-544e-4ac4-b9a6-d15828115ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comments-logout']/form/div[4]/div/div/fieldset/div/div/input</value>
      <webElementGuid>7e3c0138-0fbf-406b-9649-775a02473f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>f37ab163-22e5-4082-8fb0-79750c162c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LoginEmail' and @name = 'LoginEmail' and @placeholder = 'Email' and @type = 'text']</value>
      <webElementGuid>69db791d-e95c-472a-a1b9-0b76ea0d1582</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
