<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>04590acd-7467-4585-a550-be82e20ea190</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e533db90-f9e5-417c-b6e1-fc315813d2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f97b840e-c54f-4eac-a56f-bd162a9df49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>521d55d1-33bf-45b5-974f-d6c4995bff0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56b443a2-158f-4f9d-9610-70dbbf5ffab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-ripple font-condensed hover:bg-opacity-90 outline-none transition-all w-full md:w-1/5 md:rounded-l-none h-11 md:h-15 md:py-0 font-normal hidden md:block et-btn-accent md:text-3xl text-2xl rounded py-2 mb-10 md:mb-0 ng-tns-c105-4</value>
      <webElementGuid>23d91669-a665-4150-b663-7010010325ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search </value>
      <webElementGuid>16a6794b-5b68-4c62-b2a5-156705eab69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;cdk-global-scrollblock&quot;]/body[@class=&quot;fuse-splash-screen-hidden light theme-eteach&quot;]/app-root[1]/layout[@class=&quot;ng-star-inserted&quot;]/modern-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col w-full h-screen ng-star-inserted&quot;]/div[@class=&quot;w-full&quot;]/landing-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col items-center justify-start w-full overflow-x-hidden bg-white&quot;]/div[@class=&quot;et-background w-full&quot;]/div[@class=&quot;bg-warn md:bg-transparent w-full&quot;]/et-home-banner[1]/div[@class=&quot;pt-8 md:pt-14 md:pb-22 relative bannerWrap w-full ng-star-inserted&quot;]/search[@class=&quot;ng-tns-c105-4 search-appearance-bar ng-star-inserted&quot;]/form[@class=&quot;ng-tns-c105-4 ng-untouched ng-valid ng-star-inserted ng-dirty&quot;]/div[@class=&quot;md:px-5 lg:px-8 px-3 md:pt-6 md:pb-4 lg:w-280 lg:mx-auto md:bg-warn md:mx-4 md:rounded-md ng-tns-c105-4&quot;]/div[@class=&quot;md:flex items-center justify-between ng-tns-c105-4&quot;]/button[@class=&quot;mat-ripple font-condensed hover:bg-opacity-90 outline-none transition-all w-full md:w-1/5 md:rounded-l-none h-11 md:h-15 md:py-0 font-normal hidden md:block et-btn-accent md:text-3xl text-2xl rounded py-2 mb-10 md:mb-0 ng-tns-c105-4&quot;]</value>
      <webElementGuid>d7cfad92-270c-4197-a2a3-9283fea34d70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>84dce80c-14c4-4d3b-a473-ae12366cf990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mic_none'])[1]/following::button[2]</value>
      <webElementGuid>b3319f9d-34a0-4b7d-bcb8-3f9ee2d38b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[1]/preceding::button[1]</value>
      <webElementGuid>d7230139-2852-4cc2-9e85-f09263aed2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>d2866d1a-25e1-411c-91b6-b44baf1b8589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Search ' or . = 'Search ')]</value>
      <webElementGuid>1c69bb66-1a14-40ea-a1ed-83f1b2c9ea27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
