<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Already Registered</name>
   <tag></tag>
   <elementGuidId>1b8050a9-9335-4d79-a9dd-1140174fbc9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signuptitle1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='signuptitle1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>26912eff-7b87-42da-a474-c2d29db4b296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signuptitle1</value>
      <webElementGuid>699fa2d0-b994-4210-98a0-2ca9217da698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Already Registered?</value>
      <webElementGuid>373f73b5-7293-4b63-8005-5036e4b147b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signuptitle1&quot;)</value>
      <webElementGuid>eac721ad-42f6-4513-8847-dc7999f83abe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='signuptitle1']</value>
      <webElementGuid>43e917fd-fb37-4e27-a3d4-d3c0df300a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[2]/div/div/div/div/div/div[4]/div/div/h1</value>
      <webElementGuid>73c808ca-9f41-4816-a8fa-7c60f53d8e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application for maths teacher'])[1]/following::h1[1]</value>
      <webElementGuid>ab29b960-b626-49c0-a856-aa1f3b8f0bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Options'])[2]/following::h1[1]</value>
      <webElementGuid>a719885e-cb10-4c0d-95bf-d7e1c22d5fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIGN IN'])[1]/preceding::h1[1]</value>
      <webElementGuid>cc70bb0c-b873-48f0-a785-a55e478a75ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGISTER'])[1]/preceding::h1[1]</value>
      <webElementGuid>5d83c933-14ea-4a63-9d21-70fbd1048cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Already Registered?']/parent::*</value>
      <webElementGuid>fb9a9c5a-d91d-41f4-84ea-ba0beaffb34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>913f9631-1fb9-4e09-a982-5687484d0beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'signuptitle1' and (text() = 'Already Registered?' or . = 'Already Registered?')]</value>
      <webElementGuid>943f8499-2f85-49cd-b10c-dccac20ff506</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
