<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_LoginEmail</name>
   <tag></tag>
   <elementGuidId>9289b10f-260d-4065-8bea-ed24480813b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc9e5752-0dc1-4e2d-bac3-b568d8aea69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginEmail</value>
      <webElementGuid>4e9238ad-bd4a-46f4-8f84-9f0403d1a6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginEmail</value>
      <webElementGuid>fadf58a3-6b5b-4048-a4cd-9749651ec689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>dfcff982-83f9-429e-9d81-786c55467621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>914c75be-ee04-4abf-9077-76c82a75d9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginEmail&quot;)</value>
      <webElementGuid>6e5a8c22-f74f-4d68-ac36-00bc2ffaf354</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginEmail']</value>
      <webElementGuid>10fc2f23-d8f2-47e2-8b20-8c87379bab8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comments-logout']/form/div[4]/div/div/fieldset/div/div/input</value>
      <webElementGuid>4810f50b-1fa3-4c36-9f6c-9f54efeea089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>de2d78b0-e1b3-4223-a4b2-b06e555ca254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LoginEmail' and @name = 'LoginEmail' and @placeholder = 'Email' and @type = 'text']</value>
      <webElementGuid>730e42bc-607f-41bc-b138-a1b9ebe0c494</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
