<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forgotten password_Log in</name>
   <tag></tag>
   <elementGuidId>96c675c7-34fa-49bc-b1e5-8ddc4d29a1b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd68abe5-fa54-4cca-b906-24de3110e764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>90659c3b-b3bd-495b-9945-157985c89455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signin</value>
      <webElementGuid>89de0a85-9312-4fad-b029-66dc395c272c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>153c02ba-e9ab-4084-aa92-a5f6fbbbb1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>2c63397c-aed5-4fa0-be8c-4165eb315c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn apply-btn</value>
      <webElementGuid>ee5d85b3-1c7b-4090-93be-5cb9e5c3220b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin&quot;)</value>
      <webElementGuid>437e024a-bac0-44a9-b9bc-86eb44023446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signin']</value>
      <webElementGuid>90b83ab2-402e-4b6e-8002-07775d84f5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comments-logout']/form/div[4]/div/div/fieldset/div[3]/div/div[2]/input</value>
      <webElementGuid>1fe28975-146e-41fe-9a72-a64587f77770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>29e1d1c5-9d74-4224-b3d5-2bc3865a1a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'signin' and @name = 'Log in']</value>
      <webElementGuid>464930de-84fb-41d7-b64d-e2328ff7cfcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
