<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>304d33ae-99d9-4e45-b2fb-5964cd024693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0855660-9c8e-44cf-bf38-8734b36e15b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8c13f1b9-f7b0-40f4-9606-5d8063338e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8edd9b38-ca5e-4955-b5ab-f5ba237b503b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e66ae108-af59-4131-bdac-0d7f79556ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-ripple font-condensed hover:bg-opacity-90 outline-none transition-all w-full md:w-1/5 md:rounded-l-none h-11 md:h-15 md:py-0 font-normal hidden md:block et-btn-accent md:text-3xl text-2xl rounded py-2 mb-10 md:mb-0 ng-tns-c105-4</value>
      <webElementGuid>2935674b-1f87-486c-970f-6aeb9db7c9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search </value>
      <webElementGuid>fe8f9442-d0d0-48bf-8362-11a44f128133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;cdk-global-scrollblock&quot;]/body[@class=&quot;fuse-splash-screen-hidden light theme-fejobs&quot;]/app-root[1]/layout[@class=&quot;ng-star-inserted&quot;]/modern-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col w-full h-screen ng-star-inserted&quot;]/div[@class=&quot;w-full&quot;]/landing-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col items-center justify-start w-full overflow-x-hidden bg-white&quot;]/div[@class=&quot;et-background w-full&quot;]/div[@class=&quot;bg-warn md:bg-transparent w-full&quot;]/et-home-banner[1]/div[@class=&quot;pt-8 md:pt-14 md:pb-22 relative bannerWrap w-full ng-star-inserted&quot;]/search[@class=&quot;ng-tns-c105-4 search-appearance-bar ng-star-inserted&quot;]/form[@class=&quot;ng-tns-c105-4 ng-untouched ng-valid ng-star-inserted ng-dirty&quot;]/div[@class=&quot;md:px-5 lg:px-8 px-3 md:pt-6 md:pb-4 lg:w-280 lg:mx-auto md:bg-warn md:mx-4 md:rounded-md ng-tns-c105-4&quot;]/div[@class=&quot;md:flex items-center justify-between ng-tns-c105-4&quot;]/button[@class=&quot;mat-ripple font-condensed hover:bg-opacity-90 outline-none transition-all w-full md:w-1/5 md:rounded-l-none h-11 md:h-15 md:py-0 font-normal hidden md:block et-btn-accent md:text-3xl text-2xl rounded py-2 mb-10 md:mb-0 ng-tns-c105-4&quot;]</value>
      <webElementGuid>1c4e0b18-9ef1-4ca1-b300-47e070c54984</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>ec575858-64d8-40e2-a31d-b12d2159c864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JL'])[1]/following::button[2]</value>
      <webElementGuid>608d9d69-360e-4d69-aa82-3ee2af07daf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[1]/preceding::button[1]</value>
      <webElementGuid>fd1d8c3e-0210-4dfb-876e-627473750281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>f3151632-a8f6-4d9a-b027-80e5023d1670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>68cee20a-82ce-470f-b517-3a225e4cf712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Search ' or . = 'Search ')]</value>
      <webElementGuid>8a9e3a1b-2474-4b0a-8a3d-63a2e3ff040c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
