<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_More Options_term</name>
   <tag></tag>
   <elementGuidId>39a2cd79-16bb-4890-b755-7ca1147f0923</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchbx']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchbx</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e081a13-35fe-4c50-b72c-8dd7402dc1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f593fbd3-f58d-4e2c-82cc-4ac3aaea45e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>term</value>
      <webElementGuid>a7ba0145-056a-47d0-ac34-edd525ef2407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchfield</value>
      <webElementGuid>6055e156-f7d3-4faa-95ea-34182182c739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Blog</value>
      <webElementGuid>5ee33b32-2e92-4e62-8376-af48ae0702ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchbx</value>
      <webElementGuid>31cb1775-0ea5-4571-a034-d0ab33a0c048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>updateSection();</value>
      <webElementGuid>7b7f49a8-9bf2-4b69-ae91-c71f487959ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b6ae651-7f06-43a2-840d-b3a84a69eff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchbx&quot;)</value>
      <webElementGuid>e33d50b4-55bb-4235-abb8-82eb4b793efb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchbx']</value>
      <webElementGuid>7c405b25-bc87-4605-9a36-8d9306135370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[2]/div/div[2]/div[2]/div/div/ul/li/div/form/input</value>
      <webElementGuid>2b9b0f85-f6d8-44e9-bcc3-516c87e7c9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>6797db02-03a5-401e-9657-5c691424b318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'term' and @placeholder = 'Search Blog' and @id = 'searchbx']</value>
      <webElementGuid>8738d13b-19ec-484a-b9e0-9c06f73fba00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
