<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Eteach is an education technology busine_147cbe</name>
   <tag></tag>
   <elementGuidId>eb1dc010-5a08-4f35-ba0c-b69c6d8b57a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top-scroll']/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>529993d1-2645-4f98-b4bc-42f2017af497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>eedc203a-fd59-4c87-b9ef-7d9c6fc197b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eteach is an education technology business dedicated to providing online recruitment advertising, direct recruitment services and recruitment software to more than 7,500 schools and colleges globally</value>
      <webElementGuid>bf92cccb-45ae-4d62-a71e-972a1b8ef982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-scroll&quot;)/div[@class=&quot;main-foot-divhold&quot;]/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;container-fluid account-detail-hold&quot;]/div[@class=&quot;umb-grid&quot;]/div[@class=&quot;grid-section&quot;]/div[@class=&quot;promo-text&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row clearfix&quot;]/div[@class=&quot;col-md-12 column&quot;]/div[@class=&quot;pt-50 pb-50&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-offset-1 col-sm-10 text-center&quot;]/h1[@class=&quot;heading&quot;]</value>
      <webElementGuid>97e007bf-9ce5-484e-a2f7-74c1521e9b52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/h1</value>
      <webElementGuid>3df32b36-53ee-43bd-87ee-b79c580dd74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Call me back'])[2]/following::h1[1]</value>
      <webElementGuid>01149c7b-df3e-49b0-abc4-2a8a4957c9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Packages'])[2]/following::h1[1]</value>
      <webElementGuid>972fbbf3-d1cb-4efe-bfa2-11d398b6aed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our services'])[1]/preceding::h1[1]</value>
      <webElementGuid>0cfa0391-5752-42c0-bc95-e49119dcc405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advertise with us'])[1]/preceding::h1[1]</value>
      <webElementGuid>63a77e06-e746-4f28-a875-239e50e083f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eteach is an education technology business dedicated to providing online recruitment advertising, direct recruitment services and recruitment software to more than 7,500 schools and colleges globally']/parent::*</value>
      <webElementGuid>fbc5ba67-baca-4933-9945-231947bbb997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>cf5afdde-4d83-4325-91fd-fd22d563491a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Eteach is an education technology business dedicated to providing online recruitment advertising, direct recruitment services and recruitment software to more than 7,500 schools and colleges globally' or . = 'Eteach is an education technology business dedicated to providing online recruitment advertising, direct recruitment services and recruitment software to more than 7,500 schools and colleges globally')]</value>
      <webElementGuid>cdf21c5d-d32d-4250-89e7-d5b069f41906</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
