<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>b7e0c596-d787-4a93-92fc-d9e8321738d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92a2d791-19c6-42b4-917c-adb4a413fb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bf9d073e-d7d6-4fd6-879c-c33653f4c6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>63bf7a0d-aa34-478b-b948-dac6800b234d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>594e91f5-d806-4fc1-8768-ca98fce7b55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-ripple font-condensed hover:bg-opacity-90 outline-none transition-all w-full md:w-1/5 md:rounded-l-none h-11 md:h-15 md:py-0 font-normal hidden md:block et-btn-accent md:text-3xl text-2xl rounded py-2 mb-10 md:mb-0 ng-tns-c105-4</value>
      <webElementGuid>e0e3fba3-2b9a-4b0a-b978-f4fe81927157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search </value>
      <webElementGuid>6d54b518-4f2e-4623-9b84-bbb84cdf7503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;fuse-splash-screen-hidden light theme-fejobs&quot;]/app-root[1]/layout[@class=&quot;ng-star-inserted&quot;]/modern-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col w-full h-screen ng-star-inserted&quot;]/div[@class=&quot;w-full&quot;]/landing-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-col items-center justify-start w-full overflow-x-hidden bg-white&quot;]/div[@class=&quot;et-background w-full&quot;]/div[@class=&quot;bg-warn md:bg-transparent w-full&quot;]/et-home-banner[1]/div[@class=&quot;pt-8 md:pt-14 md:pb-22 relative bannerWrap w-full ng-star-inserted&quot;]/search[@class=&quot;ng-tns-c105-4 search-appearance-bar ng-star-inserted&quot;]/form[@class=&quot;ng-tns-c105-4 ng-untouched ng-valid ng-star-inserted ng-dirty&quot;]/div[@class=&quot;md:px-5 lg:px-8 px-3 md:pt-6 md:pb-4 lg:w-280 lg:mx-auto md:bg-warn md:mx-4 md:rounded-md ng-tns-c105-4&quot;]/div[@class=&quot;md:flex items-center justify-between ng-tns-c105-4&quot;]/button[@class=&quot;mat-ripple font-condensed hover:bg-opacity-90 outline-none transition-all w-full md:w-1/5 md:rounded-l-none h-11 md:h-15 md:py-0 font-normal hidden md:block et-btn-accent md:text-3xl text-2xl rounded py-2 mb-10 md:mb-0 ng-tns-c105-4&quot;]</value>
      <webElementGuid>71093e8b-84d2-4159-83e9-530e3bc6fc36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>0ea66426-2720-4cc1-9732-a0d05a58bbe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JL'])[1]/following::button[3]</value>
      <webElementGuid>eee6d47e-21ca-4eca-bd6c-9c47a5bf7dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[1]/preceding::button[1]</value>
      <webElementGuid>46babda8-4e2d-41c5-9095-27f15a72061d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>1d083b50-7f18-4b36-a856-f004883c7dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>4748da42-5452-480b-9461-c61fbad69d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Search ' or . = 'Search ')]</value>
      <webElementGuid>2c15218a-8cf6-4462-ab99-8cccf15440cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
