<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard</name>
   <tag></tag>
   <elementGuidId>71d16cdc-f66c-4a6d-a1e0-e9a03ee4f5e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top-scroll']/div[3]/div/div[4]/div[2]/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.your_account_hold > ul > li > a.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c6ee000-1619-4408-994c-00008d20a62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jobseekers/dashboard/</value>
      <webElementGuid>2e9112ad-7150-4403-8560-b06170ea9601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>78ba1ab1-47cf-4fe3-9d93-a700cf433e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>bd9f9c7f-3fdf-45fc-b91c-d4b087f5a180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-scroll&quot;)/div[@class=&quot;main-foot-divhold candidate-indexhold&quot;]/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;container-fluid account-detail-hold&quot;]/div[@class=&quot;main-candi-menu&quot;]/div[@class=&quot;myaccount_hold container&quot;]/div[@class=&quot;your_account_hold&quot;]/ul[1]/li[1]/a[@class=&quot;active&quot;]</value>
      <webElementGuid>e7384be6-1087-4af1-9aa6-b7f573ad6ef3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[3]/div/div[4]/div[2]/div/div/ul/li/a</value>
      <webElementGuid>7d953e1a-7dfb-479d-b3b1-5bd50397c1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Dashboard')])[2]</value>
      <webElementGuid>3a7bcec5-aaaa-4569-9360-5179ff43a45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>0d304509-4fcc-47e1-95dd-645b804b13f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please update your latest CV'])[1]/following::a[2]</value>
      <webElementGuid>36d2b61b-2e38-4f3a-9f46-3345b036a53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CV/Resume'])[1]/preceding::a[1]</value>
      <webElementGuid>e58b6999-7786-4abf-a5b4-a5c81e370342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Alerts'])[1]/preceding::a[2]</value>
      <webElementGuid>0eb1d813-d3c7-4f5f-9b13-a32b94d5b236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/jobseekers/dashboard/')])[3]</value>
      <webElementGuid>e313f268-19aa-43a7-95ae-e4159c96ff94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/a</value>
      <webElementGuid>599aaa09-b2a7-4cd8-b4a3-5bd6f349d1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/jobseekers/dashboard/' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>2773db69-0836-40b2-a4ec-8002c4507984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
