<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_LoginPassword</name>
   <tag></tag>
   <elementGuidId>014f7fa4-495a-4d0e-bb5e-0ce595fe39f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LoginPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96478a71-5e67-49a6-bfd6-94801a65099d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>8d52e0d2-7838-4d24-ad0f-3b2a8bcbf87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginPassword</value>
      <webElementGuid>9e1fb098-449a-4fe3-80b2-9f3d1c770c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginPassword</value>
      <webElementGuid>0e8a529a-74f5-4334-92b8-e0768121c244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>f8a754b7-2f9f-4877-b87b-c2ba07b24e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>aea39942-fd40-4eab-a9b0-6982ed3003ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginPassword&quot;)</value>
      <webElementGuid>bf240cf4-2b47-4610-ad50-18adc3a8ccad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginPassword']</value>
      <webElementGuid>a0a9d519-ccd5-45f9-8df6-51bf29866e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comments-logout']/form/div[4]/div/div/fieldset/div[2]/div/input</value>
      <webElementGuid>4b07215e-4614-49d1-98d6-5a6ed03977f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/input</value>
      <webElementGuid>4e5afcbd-a3b5-46dd-881f-70241ed91bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LoginPassword' and @name = 'LoginPassword' and @placeholder = 'Password' and @type = 'password']</value>
      <webElementGuid>8e631e71-2cd2-4e28-8e0f-565535840658</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
