<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>11fc18ed-42ec-49dd-bb71-719d230dae73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top-scroll']/div[2]/div/div/div/div[2]/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Eteach&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>84d99ff6-d945-4e05-b51e-51ff9e4289e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/UI/Default/Images/eteach/logo-text.svg</value>
      <webElementGuid>7d350782-efdf-425b-ab31-1fa73536cbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Eteach</value>
      <webElementGuid>f363331c-78c2-4e06-beff-22a8e7c05b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-scroll&quot;)/div[@class=&quot;main-foot-divhold&quot;]/div[@class=&quot;container-fluid whole-wrap&quot;]/div[@class=&quot;header-fullwidth&quot;]/div[@class=&quot;main-menu-hold&quot;]/div[@class=&quot;header-fullwidth&quot;]/div[@class=&quot;main-menu-hold&quot;]/div[@class=&quot;container-fluid responsive-nav-head&quot;]/div[@class=&quot;header-container&quot;]/div[@class=&quot;mainnav&quot;]/a[@class=&quot;Eteachnew logosm-hold&quot;]/img[1]</value>
      <webElementGuid>1b881dd4-32d1-4a88-9a3f-35af0ed51876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top-scroll']/div[2]/div/div/div/div[2]/div/div/div/div/a/img</value>
      <webElementGuid>ea511021-1f69-4300-8304-5051f452d8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Eteach']</value>
      <webElementGuid>70e2fbba-c795-4da3-84f6-b00fe0464254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>bef40847-2ec6-435f-b4dd-152bbc80315d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/UI/Default/Images/eteach/logo-text.svg' and @alt = 'Eteach']</value>
      <webElementGuid>88d77a6b-fbc2-42ca-bf05-86189cd3bbe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
